services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: payments-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_password123
      - MSSQL_PID=Developer
    ports:
      - "1435:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"Your_password123\" -Q \"SELECT 1\""]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - payments-network

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: payments-azurite
    command: azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --loose
    ports:
      - "10006:10000"
      - "10007:10001"
      - "10008:10002"
    networks:
      - payments-network

  payments-api:
    build:
      context: .
    image: cloudgames-payments-test
    container_name: payments-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__PaymentsDb=Server=sqlserver,1433;Database=CloudGames.Payments;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False;
      - ConnectionStrings__Storage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      - Services__GamesApi=http://localhost:5002
    ports:
      - "5003:8080"
    depends_on:
      - sqlserver
      - azurite
    networks:
      - payments-network

volumes:
  sqlserver-data:

networks:
  payments-network:
    driver: bridge

